### ISSUE TITLE
Remix when signed out doesn't work

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#127] opened 2018-11-06 17:11 UTC
Start signed out.  Hit remix - goes to sign in page.  Sign in.  This lands you on the dashboard home page rather than the remixed project.

**Comment by boatmarina** [comment] 2018-11-06 17:52
Other potential issues:  if you are logged in (and maybe have certain account permissions?), hitting remix doesn't actually take you to the project either

**Comment by boatmarina** [comment] 2018-11-06 17:55
i'm seeing remix not work for these accounts:  marina+teacher@code.org; marina+elem@code.org

**Comment by ryansloan** [comment] 2018-11-07 21:42
This seems to be fixed with the change to no longer require levelbuilder permissions on /p/dance, and we confirmed with Marina's accounts yesterday.

**Closed by ryansloan** 2018-11-07 21:42 UTC
