### ISSUE TITLE
Tints don't work when two RGB values are the same

### ISSUE THREAD

**Issue by jmkulwik** [code-dot-org/dance-party#276] opened 2018-11-12 21:18 UTC
Anything with R=G=B or G=B turns red (153,0,0). Anything R=G turns either dark blue or drab (0,0,153) or (153,153,0). Anything R=B turns magenta (153,0,153)
<img width="994" alt="tint3" src="https://user-images.githubusercontent.com/8324574/48375616-5e2b5a00-e67d-11e8-9733-2141f1fc28aa.PNG">
<img width="1026" alt="tint1" src="https://user-images.githubusercontent.com/8324574/48375618-5ec3f080-e67d-11e8-880f-031d00b2d444.PNG">
<img width="1011" alt="tint2" src="https://user-images.githubusercontent.com/8324574/48375619-5ec3f080-e67d-11e8-9ce7-c26a463b6ecc.PNG">

**Comment by boatmarina** [comment] 2018-11-16 19:56
This is pretty bad actually - setting tint to different colors results in the same experience - feels broken.  moving to csedweek milestone

**Comment by joshlory** [comment] 2018-11-19 17:58
Duplicate of issue https://github.com/code-dot-org/dance-party/issues/78?

**Comment by boatmarina** [comment] 2018-11-19 19:51
Fixing by fixing issue #240

**Closed by boatmarina** 2018-11-19 19:51 UTC
Labels: p1, won't fix
