### ISSUE TITLE
Crash when using tint on iOS

### ISSUE THREAD

**Issue by islemaster** [code-dot-org/dance-party#387] opened 2018-11-14 21:11 UTC
[This project](https://studio.code.org/projects/dance/-9BgFCKwWnZfmNfYbu6XFHIT7cOfRBZPhWz2p3w4k1E) consistently crashes after a few beats on iOS.

In-office repros:
- JoshC, iPhone 6, iOS 12.1
- Anthony, iPhone X
- JoshC, desktop Safari, doesn't crash but gets this warning:
  ![image 1](https://user-images.githubusercontent.com/1615761/48512588-b34aa580-e80e-11e8-9066-42786593cc4c.png)

No-repro on:
- Brad, Nexus 6P, Chrome 70.0
- Brad, Nexus 6P, Firefox 63.0
- Brad, Ubuntu 18.04.1 (desktop), Chrome 70.0
- Brad, Ubuntu 18.04.1 (desktop), Firefox 63.0

I've [added this scenario to our stress test suite](https://github.com/code-dot-org/dance-stress-test/commit/c014e01a78edd55f305c77fb2408e61c6e13df52).

**Comment by islemaster** [comment] 2018-11-14 21:11
![image](https://user-images.githubusercontent.com/1615761/48512648-dc6b3600-e80e-11e8-8d61-e5e476201616.png)

**Comment by mrjoshida** [comment] 2018-11-14 22:00
Another project that’s crashing my phone browser https://studio.code.org/projects/dance/AjYVG-KFNNp5UlNF35SrKE-H7ZUyYtigEeuooyK0FfI

**Comment by islemaster** [comment] 2018-11-14 22:08
That one's pretty minimal; my best guess at this point is a Safari-specific memory leak with `tint()`.

**Comment by ryansloan** [comment] 2018-11-15 00:48
Yep, it's `tint()`. I remixed, verified that it crashes on my iPhone, then removed tint and reran without crashing. This seems to be a regression, because I can no longer pass puzzle 8 on my iPhone either.

**Comment by ryansloan** [comment] 2018-11-15 01:01
Can confirm this is also busted on the office iPad. I will try on a newer iPad, but this should be fixed. It also seems like a regression, since I was testing the puzzles on my iPhone as recently as last week.

**Comment by ryansloan** [comment] 2018-11-15 04:00
Two recent PRs related to this:
https://github.com/code-dot-org/p5.play/pull/48
https://github.com/code-dot-org/p5.play/pull/46

**Comment by islemaster** [comment] 2018-11-15 05:43
We published `dance-party@0.0.31` with an out-of-date p5.play dependency baked in, so it was missing the `tint()` optimizations we made recently to accommodate the larger spritesheets.  I've pushed an update to our publishing script to ensure we update dependencies before build and publish.  The fix should easily go out tomorrow provided we pick up a new dance-party build in the main repo.

**Comment by joshlory** [comment] 2018-11-16 02:16
Fixed with https://github.com/code-dot-org/code-dot-org/pull/26105.  Sorry all!

**Closed by joshlory** 2018-11-16 02:16 UTC
Labels: crashes, p0
