### ISSUE TITLE
level 12 validation 

### ISSUE THREAD

**Issue by brook-osborne** [code-dot-org/dance-party#203] opened 2018-11-08 01:42 UTC
chrome, mac

level passes with starter code

**Comment by boatmarina** [comment] 2018-11-14 18:52
@mrjoshida is this on your radar to add validation to level 12?  i still repro this

**Comment by boatmarina** [comment] 2018-11-18 18:31
duplicate of #333 where i see more activity, so closing this one

**Closed by boatmarina** 2018-11-18 18:31 UTC
Labels: curriculum
