### ISSUE TITLE
[Polish] "View teacher guide" link seems too high on tiles

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#412] opened 2018-11-16 00:50 UTC
On https://code.org/hourofcode/overview tiles, the "View teacher guide" looks like it's higher than it's supposed to be:
![image](https://user-images.githubusercontent.com/16227893/48590946-693cef00-e8f6-11e8-9eed-c7d603005e47.png)

In some languages, this also causes the link to conflict with the text:
![image](https://user-images.githubusercontent.com/16227893/48590966-8245a000-e8f6-11e8-815f-f08fdb26f0d5.png)

**Comment by boatmarina** [comment] 2018-11-18 18:16
duplicate of #371

**Closed by boatmarina** 2018-11-18 18:16 UTC
