### ISSUE TITLE
level 9 - left_shark imperceptible change

### ISSUE THREAD

**Issue by bakerfranke** [code-dot-org/dance-party#144] opened 2018-11-06 21:03 UTC
on level 9 the setup has `left_shark begins height following bass`.  But when you run the code, the shark's height never changes.  Perhaps using size as the default here would be better.

But begs the question: what does height do?

**Comment by ryansloan** [comment] 2018-11-07 02:19
dupe of #83

**Closed by ryansloan** 2018-11-07 02:19 UTC
Labels: duplicate
