### ISSUE TITLE
issues seeing things on phone

### ISSUE THREAD

**Issue by alicesteinglass** [code-dot-org/dance-party#358] opened 2018-11-13 07:21 UTC
Level 1 of dance party 2 does not have responsive layout.

Some of the levels in dance party part 1 have blocks that are too wide to work on a small phone.

**Comment by joshlory** [comment] 2018-11-13 17:23
Duplicate of issue https://github.com/code-dot-org/dance-party/issues/210?

**Comment by boatmarina** [comment] 2018-11-13 18:34
the second part of the bug is a duplicate of issue #210 but the first part is about just the first level of dance party 2 which is currently an HTML page.  If the HTML page is translateable, this gives us the ability to make the tiles look better on desktop at the cost of not being responsive on mobile.  I think that's a good trade-off to make.  

(Note, if it turns out that the HTML page is not actually translateable after all, we may end up switching to an MD page for this level which I think then WOULD make this responsive.)

Given that there's a bug tracking the 2nd part of this issue, i'm going to won't fix this bug with the caveat above.

**Closed** 2018-11-13 18:35 UTC
