### ISSUE TITLE
Level 11 validation

### ISSUE THREAD

**Issue by mikeharv** [code-dot-org/dance-party#180] opened 2018-11-07 21:30 UTC
Level 11 hint suggests it's not just free play but you don't actually have to change anything or do what it says. The level also ends after 7 measures, not 8 as indicated.

**Comment by boatmarina** [comment] 2018-11-14 18:56
@mrjoshida same as level 12 - no validation on this level.  the fact that this level ends after 7 measures is now fixed in the hint.

**Comment by mrjoshida** [comment] 2018-11-14 18:58
Working on a solution for 10 and 11 https://github.com/code-dot-org/dance-party/pull/373 - probably nothing we can do for 12

**Comment by breville** [comment] 2018-11-15 12:12
Regarding the level finishing early... that was supposed to be fixed with https://github.com/code-dot-org/dance-party/issues/313.  Was that fix not applied to all levels, or did it regress?

**Comment by boatmarina** [comment] 2018-11-18 18:31
duplicate of #332 so closing this one

**Closed by boatmarina** 2018-11-18 18:31 UTC
Labels: curriculum
