### ISSUE TITLE
Level 2: After X Measures Block in Toolbox

### ISSUE THREAD

**Issue by dmcavoy** [code-dot-org/dance-party#380] opened 2018-11-14 14:52 UTC
The video suggests that you should be able to pull the measures block from the toolbox - I get that the level is already seeded with it out but should any of the blocks that the level is seeded with be in the toolbox?

**Comment by boatmarina** [comment] 2018-11-14 18:34
this was an intentional decision in the video that Hadi wanted us to include (so you knew there were more events than just the one.)  but i believe it's intentional that we only want the one block in level 2 to scope down what you're able to do in this level.  @mrjoshida to see that i'm closing this as by design in case i'm wrong. :)

**Closed by boatmarina** 2018-11-14 18:34 UTC
Labels: curriculum
