### ISSUE TITLE
Pineapple clap high animation missing?

### ISSUE THREAD

**Issue by mikeharv** [code-dot-org/dance-party#179] opened 2018-11-07 21:27 UTC
https://studio.code.org/s/dance/stage/1/puzzle/9

Set a dancer to Pineapple and press run. A cat animation is used until the code changes to a new dance after 2 measures. (The cat animation is also wrong as it's showing half of a kick instead of clap high.)

**Comment by ryansloan** [comment] 2018-11-07 21:32
Dupe of #112 and #167

**Closed by ryansloan** 2018-11-07 21:32 UTC
Labels: duplicate
