### ISSUE TITLE
"rand" move in default code for level but not in dropdown

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#347] opened 2018-11-13 05:59 UTC
I'm not sure what "rand" is here. It doesn't show up in the dropdown. But it's part of the default code in https://staging-studio.code.org/s/dance-extras/stage/1/puzzle/6. 

![image](https://user-images.githubusercontent.com/16227893/48393841-07963e00-e6c6-11e8-825a-83d360395f6b.png)

**Comment by ryansloan** [comment] 2018-11-13 17:14
Dupe of #360

**Closed by ryansloan** 2018-11-13 17:14 UTC
Labels: duplicate
