### ISSUE TITLE
Level 8: validation feedback could use more formatting

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#326] opened 2018-11-13 03:47 UTC
The validation hint just uses backticks around the block name:

![screenshot 2018-11-13 14 45 47](https://user-images.githubusercontent.com/2205926/48389719-e3347300-e752-11e8-88f9-663b0af0ee62.png)

Can we use one of the other formatting options instead, e.g.
![screenshot 2018-11-13 14 31 13](https://user-images.githubusercontent.com/2205926/48389730-ec254480-e752-11e8-8e04-b4f4c35f2426.png)

or

![screenshot 2018-11-13 14 33 09](https://user-images.githubusercontent.com/2205926/48389732-ec254480-e752-11e8-99f8-2f640042dc75.png)

**Comment by ryansloan** [comment] 2018-11-13 04:25
Dupe of #259

**Closed by ryansloan** 2018-11-13 04:25 UTC
Labels: duplicate
