### ISSUE TITLE
"Song title" background effect broken

### ISSUE THREAD

**Issue by jmkulwik** [code-dot-org/dance-party#271] opened 2018-11-12 21:08 UTC
<img width="337" alt="songtitlesecondeffect" src="https://user-images.githubusercontent.com/8324574/48375101-b5c8c600-e67b-11e8-9be3-4a2777993edf.PNG">
<img width="336" alt="songtitlesecondeffect2" src="https://user-images.githubusercontent.com/8324574/48375102-b7928980-e67b-11e8-858d-4e2b88a68242.PNG">

1. Continues to display in front of other background effects
2. Dancer gets a shadow
3. If "Song title" effect is used in the level and then the level is re-played with a new song, the "song title" effect keeps the old song title.

**Comment by ryansloan** [comment] 2018-11-12 21:33
dupe of #262

**Closed by ryansloan** 2018-11-12 21:33 UTC
Labels: duplicate
